### ISSUE TITLE
Cannot call methods that take MwFastBuffer as an input

### ISSUE THREAD

**Issue by GlenMartens** [openplanet-nl/issues#14]
It is currently not possible to call methods that take an MwFastBuffer as an argument, doing so will crash the game. The method I was trying to use is PlayMapList.

**Comment by DarkestSentinel** [comment]
Experiencing the same issue, in my case with the methods GetDisplayName and RetrieveDisplayName.

**Comment by codecat** [comment]
This issue actually highlights 3 separate bugs:

* Passing the wrong pointer for arguments passed as reference
* Arguments passed by reference being copied instead of simply passing a pointer
* Objects passed to `MwFastBuffer::Add` weren't being copied at all, which means the object within the buffer **could** have been invalid when passed to the proc

I've fixed all of these 3 issues.

However, there can be some memory leakage happening when working with `MwFastBuffer` destructors due to [this potential Angelscript bug](https://www.gamedev.net/forums/topic/711330-unable-to-get-subtype-id-from-asiscriptgeneric-in-destructor/). I've opened #22 for this, which I'm considering high priority. Hopefully this will be fixed soon!

Additionally, `MwFastArray` etc. can still have some of these issues, which I probably will get to later when the linked Angelscript issue can be resolved.
