### ISSUE TITLE
UI::Markdown heredoc strings cause ambiguous error logs

### ISSUE THREAD

**Issue by nitroquery** [openplanet-nl/issues#26]
e.g.
```
class Example {
  // Following prints error  "Unexpected \x20 of type WHITESPACE, was expecting a WORD"
  void Markdown() {
      UI::Markdown("""
# Markdown
      """);
  }
  // While this does not
  void Text() {
      UI::Text("""
TEXT
      """);
  }
}
```

**Comment by skybaks** [comment]
I can only imagine this is because the `#` is being picked up by the preprocessor

**Comment by codecat** [comment]
Indeed, this error comes from ccpp:
https://github.com/codecat/ccpp/blob/bf9bd0b8dfe83444a5bff5d0ecf7ad8e34602fc7/ccpp.h#L248-L261
I'm not sure it warrants fixing in this specific case, considering this is the expected behavior of the preprocessor. Your best bet is to do something like this instead:
```asc
void Markdown()
{
  UI::Markdown(
    "# Markdown\n"
    "This is a test"
  );
}
```
