### ISSUE TITLE
Openplanet causes break activation after checkpoint

### ISSUE THREAD

**Issue by SucherWild** [openplanet-nl/issues#32]
I just installed Openplanet, now I am experiencing sudden random breaking (while not holding key) after checkpoints.
Tapping break usually resolves, but it does lose prescious time every time it happens.
Is respawnable unless break tapped or reset to start.
I hope this is the right place to put this :D

**Comment by codecat** [comment]
Are you sure this is caused by Openplanet? What happens if you temporarily disable Openplanet by holding down the Pause Key on your keyboard before starting the game? (Hold the key before clicking Play, release the key when the game window shows up)

It would also help to know which plugins you are using. Posting your `Openplanet.log` could help with this.

**Comment by SucherWild** [comment]
Okay, tried again, have not had the issue ever again. Maybe it just needed a game restart or a Pc reboot. Guess this can be closed :D

**Comment by codecat** [comment]
Good to hear! 👍
